### PR TITLE
Add devcontainer definition

### PR DESCRIPTION
**Pull request by o-lukas**
## :recycle: Current situation

The main benefit of the devcontainers for me is that I have everything set up and ready to go after a few minutes and do not have to struggle with setting up node, homebridge, etc. So I went with creating a devcontainer which contains a basic homebridge instance already set up and ready to use.

## :bulb: Proposed solution

Add a ready-to-use devcontainer definition.

## :gear: Release Notes

- added devcontainer definition files

## :heavy_plus_sign: Additional Information

The main benefit of the devcontainers for me is that I have everything set up and ready to go after a few minutes and do not have to struggle with setting up node, homebridge, etc. So I went with creating a devcontainer which contains a basic homebridge instance already set up and ready to use. 

I prepared a branch which contains the definition files needed to get it working. I can not push it because of permissions but you can check this [repository](https://github.com/o-lukas/homebridge-smartthings-tv/tree/main/.devcontainer) for the definition I used for my first plugin. If you tell me how to publish the branch I prepared I can do this of course so you can see the definition without my plugin specific stuff.

### Testing

I have used the container for developing a plugin and have fixed the issues I have found while using it. So I think there should be no (major) problems.

### CODE REVIEW

**Comment by jeff-winn** [comment]
How does this solve the mDNS issue when adding the bridge to HomeKit?

With the solution running on the developer workstation mDNS works as expected. However when running within a container mDNS broadcasts are not forwarded and iOS cannot find the new bridge.

Without it, devs still need to do all the local setup before running in the container causing duplicate work.

**Comment by o-lukas** [comment]
Currently docker does support the option `--network host` which is used to get around this issue only on Linux systems (see [here](https://github.com/docker/roadmap/issues/238)). So the container do only work when running on Linux systems.

But you can still use the container on Mac or Windows and control your accessories using the Homebridge Config UI.

**Comment by o-lukas** [comment]
To get some more information about the problem check the [docker-homebridge repository](https://github.com/homebridge/docker-homebridge#compatibility). There are some more links about the issue.

**Comment by bwp91** [comment]
Hi @o-lukas looking into these PRs now, please rebase on `main` which i renamed from `master`

**Comment by bwp91** [comment]
Gonna close this for the following reasons:

- the docker images look old now
- there's a lot of 'extra config'
- the `auth.json` you provided contains secrets

Also don't want to make the plugin template too complicated for new user.

If you (or any other admin) disagrees with this then please reopen!!

**Comment by o-lukas** [comment]
@bwp91 Thanks for your review. 

* The PR has been laying around for quiet some time now. If this would help I can of course update the docker image to a new one. 
* I don't really see that much 'extra config' because the extra config would be necessary as well for a standalone Homebridge instance 
* the file does only contain a default `admin` account so I can disable the auth page because if there is no account the UI does not work at all. This could be removed of course but would lead to the extra step of configuring an account.

I understand you want to keep the template simple but just wanted to state my opinion to your points 😊

**Comment by bwp91** [comment]
Hi @o-lukas 
Thanks for your reply on here, of course am
happy to reopen this and appreciate the fact you made the PR in the first place. Probably didn’t come across this way in my earlier comment 🤭

**Comment by bwp91** [comment]
Can't pretend i'm an expert on the devcontainers nor have I used this before. But a couple of other comments first!

The thing in the back of my mind is always going to be that this repo is cloned by users and thus any files here are going to be part of future plugins.

1. I don't use vscode myself but would it be considered normal to have these `./.vscode/*` files as part of the repo? or instead as part of the gitignore file?
2. The `.devcontainer` files - would it not be better to have these in the npm ignore file so that when any user clones this repo to create a plugin, they would not be part of the installation?

**Comment by o-lukas** [comment]
Thanks for re-opening 😊

You can easily try the devcontainers by using the Github Codespaces. You wouldn't even have to download anything but can develop and even start a Homebridge instance. This instance would be pretty limited but you can use it for simple test cases.

Regarding your points:

1. The `.vscode` directory usually contains the VSCode settings that will be shared across developers. In this case I added the run configurations to the settings so that one can easily start debugging. They are just for convenience causes and could of course be removed.
2. I agree these should probably be added to a npm ignore file as well as the `.vscode` directory.

**Comment by jeff-winn** [comment]
I ended up walking away from devcontainers.

Biggest reason was I couldn’t add my homebridge instance running on Windows due to host network mode not being available. The avahi (I think) dependency inside hap-nodejs used to identify it’s there and seen by Apple products didn’t work and I couldn’t get it exposed.

**Pull request closed without merging**
