### PR TITLE
Use peerDependencies instead of engines since they are better suited to plugins.

### PR DESCRIPTION
**Pull request by hjdhjd**

### CODE REVIEW

**Comment by oznu** [comment]
The homebridge core looks for "homebridge" in the engine list, so this change won't work unfortunately.

Additionally, with the upcoming version of npm v7.x, peer dependencies will be installed automatically, which we don't want happening with the Homebridge package.

**Comment by hjdhjd** [comment]
LOL...as always, fascinating. @oznu at the least, that's a little abusive of the poor engine list. 😄 If someone goes to install a plugin, it **should** install homebridge if homebridge isn't already installed, don't you think?

**Comment by oznu** [comment]
>  If someone goes to install a plugin, it should install homebridge if homebridge isn't already installed, don't you think?

It will install it again under the plugins own `node_modules` folder. Also may cause problems for users that have Homebridge installed globally, but have their plugins in a custom plugin path (`-P` flag). This setup is fairly common (user by every Docker user, as it allows Homebridge and the UI to be updated as part of a container/image update, while leaving the users plugins intact and unchanged).

**Comment by hjdhjd** [comment]
Just for completeness:

https://nodejs.org/es/blog/npm/peer-dependencies/
https://nodejs.org/es/blog/npm/peer-dependencies/

I don't believe it'll reinstall them in node_modules - it will install the peer dependency if it isn't already there. Starting with npm 3, it won't install the peer dependency by default.

I still maintain that this is The Right Way to express something is a plugin of homebridge in an NPM package.json...but I defer to the more experienced.

**Comment by oznu** [comment]
See https://github.com/npm/cli/blob/latest/CHANGELOG.md#v700-beta0-2020-08-04

> RFC 25 peerDependencies are installed by default. 

---

Since plugins don't actually import Homebridge at runtime, it's not a "dependency" in the npm sense of the term. If we were to replace the "engines" section requirement, it would likely be with a custom attribute such as `"homebridge": { "version": ">= 1.2.3", "other": "metadata here"}`. There has been some discussion about this on the homebridge repo.

**Comment by hjdhjd** [comment]
@oznu I yield to your superior wisdom and appreciate the explanation. 😄

**Pull request closed without merging**
